### ISSUE TITLE
Don't use `parseInt()` on port numbers

### ISSUE THREAD

**Issue by hdpinto** [cdimascio/generator-express-no-stress-typescript#12]
Express/http will happily accept string port numbers. This is an issue with the type definitions:
`listen` should use string for port number since `createServer(app).listen( ... )` has overloads that accept a pipe/path.

```ts
listen(port: string = process.env.port): Application {
    const welcome = port => () =>
      l.info(`up and running in ${process.env.NODE_ENV || 'development'} @: ${os.hostname()} on port: ${port}}`);
    http.createServer(app).listen(port, welcome(port));
    return app;
  }
```

Using `parseInt()` breaks production deployments where a pipe is used instead of a port, since the pipe resolves to `NaN`.

**Comment by hdpinto** [comment]
If anyone is getting an invalid port error trying to deploy to Azure, see above.

**Comment by cdimascio** [comment]
@hdpinto thanks for the issue. I've updated the signature to enable both the pipe and path cases. see version 4.0.1
