### ISSUE TITLE
Automatically add .env to .gitignore

### ISSUE THREAD

**Issue by chriszrc** [cdimascio/generator-express-no-stress-typescript#2]
The accepted wisdom is that the .env file should never be committed, would be great if this was the default that the generator generated. Otherwise, looking good so far, nice!!

https://github.com/motdotla/dotenv#should-i-commit-my-env-file

**Comment by cdimascio** [comment]
thanks @chriszrc agreed. i'll fix that

**Comment by cdimascio** [comment]
fixed in 1.1.5

**Comment by chriszrc** [comment]
Nice!

**Comment by chriszrc** [comment]
I can open a nice issue if you want, but maybe this will suffice, I would have expected the build folder would also be gitignored, since that will contain the sensitive .env file, and because we don't need builds in git-

**Comment by cdimascio** [comment]
agreed.
all set, `.gitignore` is installed with the following entries:

```
build
node_modules
.env
```
