### ISSUE TITLE
controller in example does not go through `copyTpl` process

### ISSUE THREAD

**Issue by inf3cti0n95** [cdimascio/generator-express-no-stress-typescript#21]
As the `files` array does not include the path to the controller. https://github.com/cdimascio/generator-express-no-stress-typescript/blob/9d85cd337cd7475d8d962220cf6b15387afa5b1d/app/index.js#L72-L83

It does not process the [example controller ](
https://github.com/cdimascio/generator-express-no-stress-typescript/blob/master/app/templates/server/api/controllers/examples/controller.ts) through copyTpl process which replaces yoeman template strings. And as a result the method in controller remains unchanged.
https://github.com/cdimascio/generator-express-no-stress-typescript/blob/9d85cd337cd7475d8d962220cf6b15387afa5b1d/app/templates/server/api/controllers/examples/controller.ts#L20

Which is an invalid parameter for the express app.

**Comment by cdimascio** [comment]
Thanks for the fix @inf3cti0n95! It's live in v5.0.1
