### ISSUE TITLE
Missing Dockerfile

### ISSUE THREAD

**Issue by filol** [cdimascio/generator-express-no-stress-typescript#26]
I have the impression that you forgot to push the dockerfile and the docker ignores. I can't find any trace of these 2 files in your repo.

Thank you for your work ! 😄

**Comment by cdimascio** [comment]
thanks! fixed in v6.0.10

**Comment by filol** [comment]
Thanks ! There isn't a dockerignore too ?

**Comment by cdimascio** [comment]
woops! fixed in v6.0.11. thanks again
