### ISSUE TITLE
Routes not found

### ISSUE THREAD

**Issue by icecold21** [cdimascio/generator-express-no-stress-typescript#30]
Try generating new APP,
change the route from 
`app.use('/api/v1/examples',` examplesRouter);`

To 
`app.use('/api/v2/examples', examplesRouter);`

Open 
`localhost:3000/api/v2/examples`

Become 404

**Comment by kwiss** [comment]
same here

**Comment by cdimascio** [comment]
@icecold21 @kwiss 
If you generated the app with the defaults, the API root is `/api/v1`
If you want to change the root after generating the project, you nee
 to do two things:
1. Modify the middleware router in `server/routes.js` as you did e.g.
```javascript
app.use('/api/v2/examples', examplesRouter);
```

2. Modify the API root in your API description in `server/common/api.yaml`

```yaml
openapi: 3.0.1
info:
  title: myapp
  description: My cool TypeScript app
  version: 1.0.0
servers:
- url: /api/v2     #<--- change this from /api/v1 to /api/v2
```

**Comment by cdimascio** [comment]
closing this out. please let me know if you still have issues
