### ISSUE TITLE
Usability: prettier CR warnings

### ISSUE THREAD

**Issue by brakmic** [cdimascio/generator-express-no-stress-typescript#35]
Hi,

Prettier is warning because of **CR char** on Windows which should not be the case as Windows uses **CRLF** for line endings.

Regards,

**Comment by cdimascio** [comment]
Thanks @brakmic. Prettier changed the default from `auto` to `lf` in v2.0.0. in the most recent major version of this generator, we upgraded prettier. I think it makes the most sense to keep with prettier's default. For folks the need something different, they can make the change u specifies.

Thanks for you interest in the project
