### ISSUE TITLE
Documentation has typo

### ISSUE THREAD

**Issue by chriszrc** [cdimascio/generator-express-no-stress-typescript#4]
The commands to run the production build -
https://github.com/cdimascio/generator-express-no-stress-typescript#run-in-production-mode

Are missing the "run" command:
```
npm compile
npm start
```
should be
```
npm run compile
npm run start
```

**Comment by cdimascio** [comment]
thanks @chriszrc 
the following also works. will update the doc shortly

```
npm run compile
npm start
```
