### ISSUE TITLE
examples.controller.ts is wrong in template

### ISSUE THREAD

**Issue by eusorov** [cdimascio/generator-express-no-stress-typescript#5]
1.   .to.be.an.an('array')

two "an" is wrong. It should be .to.be.an('array')

2. .expect('Content-Type', /json/)
it should be a .set('Accept', 'application/json') before each expect. 
Otherwise we don't get json back from Server and the test fails.

**Comment by cdimascio** [comment]
@eusorov thanks again :). Fixed in 1.2.4
