### ISSUE TITLE
docker kill ctrl+c (SIGINT) signal does not kill the process

### ISSUE THREAD

**Issue by feyzullahyildiz** [cdimascio/generator-express-no-stress-typescript#56]
Somehow the application does not work with docker well. I cannot kill the process with ctrl+c.
I created a [simulator application](https://github.com/feyzullahyildiz/express-no-stress-typescript-bug-simulator)

```Dockerfile
FROM node:14-alpine

COPY ./package.json ./package.json
COPY ./package-lock.json ./package-lock.json
RUN npm i
COPY . .
RUN npm run compile
CMD [ "npm", "start" ]
```
## Bug Scenario
- build a docker image: `docker build . -t test-express-image`
- run a container: `docker run --name testapp -p 3000:3000 --rm test-express-image`
- try to kill the container with `ctrl+c`. The container does not die :(
- it works, when i try to kill like this: `docker kill testapp`

`docker kill` default signal is `SIGKILL`. [docker docs](https://docs.docker.com/engine/reference/commandline/kill/) 

Default Unix `ctrl+c` kill signal is `SIGINT` [a unix docs](http://www.cs.kent.edu/~ruttan/sysprog/lectures/signals.html)

I think the application ignores `SIGINT` signal.

**Comment by sujeeet-kumar** [comment]
In a docker container your app is assinged as PID 1. Node.js is not designed to run as PID 1, so it doesn't have listeners for `SIGINT`, `SIGTERM` or `SIGKILL`.

You need create those listeners in your app.

```
// quit on ctrl+c when running docker in terminal
process.on('SIGINT', async () => {
  console.info('Got SIGINT (aka ctrl+c in docker). Graceful shutdown', new Date().toISOString());
  // do graceful shutdown
});

// quit properly on docker stop
process.on('SIGTERM', async () => {
  console.log('Got SIGTERM (docker container stop).Graceful shutdown', new Date().toISOString());
  // do gracefull shutdown
});
```

For more info, have a look on this [repo](https://github.com/sujeet-agrahari/node-express-clean-architecture/blob/master/src/server.js).

**Comment by cdimascio** [comment]
@sujeeet-kumar, thanks for the info. This is great. Would you be interested in creating a PR. This is beneficial
